<?php
$routerConfig = array (
    'frontend' => array(
        'home' => array(
            'method' => 'homePage'),
        'listPosts' => array(
            'method' => 'getPostsPublished',
            'getKeys' => ['page']),
        'getPost' => array(
            'method' => 'getPostById',
            'getKeys' => ['postId', 'page']),
        'addComment' => array(
            'method' => 'addComment',
            'getKeys' => ['postId', 'page'],
            'postKeys' => ['lastName', 'firstName', 'content']),
        'report' => array(
            'method' => 'reportComment',
            'getKeys' => ['commentId', 'page']),
        'login' => array(
            'method' => 'login'),
        'connection' => array(
            'method' => 'connection',
            'postKeys' => ['login', 'password'])
    ),
    'backend' => array(
        'disconnection' => array(
            'method' => 'disconnection'),
        'writeNewPost' => array(
            'method' => 'writeNewPost'),
        'addPost' => array(
            'method' => 'addPost',
            'postKeys' => ['title', 'content', 'published']),
        'listPostsTitle' => array(
            'method' => 'listPostsTitle',
            'getKeys' => ['page']),
        'editPost' => array(
            'method' => 'editPost',
            'getKeys' => ['postId']),
        'updatePost' => array(
            'method' => 'updatePost',
            'getKeys' => ['postId'],
            'postKeys' => ['title', 'content', 'published']),
        'deletePost' => array(
            'method' => 'deletePost',
            'getKeys' => ['postId']),
        'listCommentsReport' => array(
            'method' => 'listCommentsReport',
            'getKeys' => ['page']),
        'findPageOfComment' => array(
            'method' => 'findPageOfComment',
            'getKeys' => ['commentId']),
        'deleteComment' => array(
            'method' => 'deleteComment',
            'getKeys' => ['commentId', 'page']),
        'validComment' => array(
            'method' => 'validComment',
            'getKeys' => ['commentId', 'page'])
    )
);
