<?php
$routerConfig = array (
    'Frontend' => array(
        'Accueil' => array(
            'method' => 'homePage'),
        'Chapitres' => array(
            'method' => 'getPostsPublished',
            'getKeys' => ['page']),
        'Chapitre' => array(
            'method' => 'getPostById',
            'getKeys' => ['id', 'page']),
        'Ajouter-un-commentaire' => array(
            'method' => 'addComment',
            'getKeys' => ['id'],
            'postKeys' => ['pseudo', 'content']),
        'Signaler-un-commentaire' => array(
            'method' => 'reportComment',
            'getKeys' => ['id', 'page']),
        'Connexion' => array(
            'method' => 'connection',
            'postKeys' => ['login', 'password']),
        'Erreur' => array(
            'method' => 'error')
    ),
    'Backend' => array(
        'Deconnexion' => array(
            'method' => 'disconnection'),
        'Nouveau-chapitre' => array(
            'method' => 'writeNewPost'),
        'Ajouter-chapitre' => array(
            'method' => 'addPost',
            'postKeys' => ['title', 'content', 'published']),
        'Titre-des-chapitres' => array(
            'method' => 'listPostsTitle',
            'getKeys' => ['page']),
        'Editer-un-chapitre' => array(
            'method' => 'editPost',
            'getKeys' => ['id']),
        'Enregister-le-chapitre' => array(
            'method' => 'updatePost',
            'getKeys' => ['id'],
            'postKeys' => ['title', 'content', 'published']),
        'Supprimer-le-chapitre' => array(
            'method' => 'deletePost',
            'getKeys' => ['id']),
        'Liste-des-commentaires' => array(
            'method' => 'listCommentsReport',
            'getKeys' => ['page']),
        'Voir-le-context' => array(
            'method' => 'findPageOfComment',
            'getKeys' => ['id']),
        'Supprimer-le-commentaire' => array(
            'method' => 'deleteComment',
            'getKeys' => ['id', 'page', 'redirection']),
        'Valider-le-commentaire' => array(
            'method' => 'validComment',
            'getKeys' => ['id', 'page'])
    )
);
